-- ============================================================================
-- Day 3 — Database, Roles & Security Foundation
-- College Complaint Management System (ECS MVP pilot)
--
-- Run this ONCE in the Supabase SQL editor (or via `supabase db push`).
-- It is idempotent: most statements are guarded so it can be re-run safely,
-- but re-running is not required.
--
-- What this migration creates:
--   * enums          : app_role, priority_level, complaint_status,
--                      handler_type, sender_role, reveal_status
--   * tables         : profiles, departments, complaint_categories,
--                      category_department_map, complaints, messages,
--                      identity_reveal_requests
--   * seed data      : ECS department, the 8 ECS complaint categories,
--                      category -> ECS mapping
--   * functions      : get_app_role, can_access_complaint,
--                      handle_new_user, derive_complaint_defaults,
--                      messages_set_sender, set_updated_at
--   * triggers       : profile auto-creation on sign-up, ticket number
--                      generation, sensitivity/handler/department derivation,
--                      message sender normalization, updated_at
--   * RLS            : enabled on every table + per-role policies
--   * views          : complaints_staff_view, messages_staff_view
--                      (security invoker, identity-free projections)
--   * indexes        : MVP access-pattern indexes
--
-- SECURITY MODEL (summary)
--   * Authoritative role lives ONLY in public.profiles.role. Auth user
--     metadata is never authoritative. A sign-up trigger creates the profile
--     with role 'student'.
--   * Profiles have a select-own-only policy and NO update policy at all:
--     a normal student cannot change role or department_id via the API.
--   * The base complaints/messages tables hide identity COLUMNS
--     (student_id, sender_id) from `authenticated` via column-level grants,
--     and row visibility is controlled by RLS. Staff/admin/committee read
--     complaints through the identity-free staff views, which are
--     security-invoker views so the underlying RLS is respected.
--   * Ticket numbers are generated by a PostgreSQL sequence in a trigger
--     (atomic, collision-safe, CMP-XXXX format).
--   * No secret keys (sb_secret_*) are used anywhere in this migration or
--     in the React app. service_role is never used in frontend code.
-- ============================================================================

-- ============================================================================
-- 1. ENUMS (guarded so the migration can be re-run safely)
-- ============================================================================

do $$
begin
  if not exists (select 1 from pg_type where typname = 'app_role' and typnamespace = 'public'::regnamespace) then
    create type public.app_role as enum ('student', 'faculty', 'admin', 'committee');
  end if;
end
$$;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'priority_level' and typnamespace = 'public'::regnamespace) then
    create type public.priority_level as enum ('low', 'medium', 'high', 'urgent');
  end if;
end
$$;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'complaint_status' and typnamespace = 'public'::regnamespace) then
    create type public.complaint_status as enum (
      'submitted',
      'under_review',
      'assigned',
      'in_progress',
      'resolved',
      'reopened',
      'escalated',
      'closed'
    );
  end if;
end
$$;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'handler_type' and typnamespace = 'public'::regnamespace) then
    create type public.handler_type as enum ('department', 'committee');
  end if;
end
$$;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'sender_role' and typnamespace = 'public'::regnamespace) then
    create type public.sender_role as enum ('student', 'staff', 'committee');
  end if;
end
$$;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'reveal_status' and typnamespace = 'public'::regnamespace) then
    create type public.reveal_status as enum ('pending', 'consented', 'denied');
  end if;
end
$$;

-- ============================================================================
-- 2. TABLES
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 2.1 departments — only ECS exists for this MVP. No fake departments.
-- ----------------------------------------------------------------------------
create table if not exists public.departments (
  id         uuid primary key default gen_random_uuid(),
  name       text not null unique,
  created_at timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
-- 2.2 profiles — the authoritative application role lives here.
--     id -> auth.users.id (mirrored by the sign-up trigger).
-- ----------------------------------------------------------------------------
create table if not exists public.profiles (
  id            uuid primary key references auth.users (id) on delete cascade,
  email         text not null,
  role          public.app_role not null default 'student',
  department_id uuid references public.departments (id) on delete set null,
  created_at    timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
-- 2.3 complaint_categories — the eight ECS categories.
--     Harassment / Ragging is sensitive; everything else is not.
-- ----------------------------------------------------------------------------
create table if not exists public.complaint_categories (
  id           uuid primary key default gen_random_uuid(),
  name         text not null unique,
  is_sensitive boolean not null default false,
  created_at   timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
-- 2.4 category_department_map — routing table (category -> department).
--     Keeps routing flexible for future expansion without hardcoding
--     category logic into the departments table.
-- ----------------------------------------------------------------------------
create table if not exists public.category_department_map (
  category_id   uuid not null references public.complaint_categories (id) on delete cascade,
  department_id uuid not null references public.departments (id) on delete cascade,
  primary key (category_id, department_id)
);

-- ----------------------------------------------------------------------------
-- 2.5 complaints — anonymous complaint records. Identity fields are never
--     exposed to staff through the application-facing API (see grants below).
-- ----------------------------------------------------------------------------
create table if not exists public.complaints (
  id             uuid primary key default gen_random_uuid(),
  ticket_number  text not null unique,                    -- CMP-XXXX, sequence-generated
  student_id     uuid not null references public.profiles (id) on delete cascade,
  category_id    uuid not null references public.complaint_categories (id) on delete restrict,
  department_id  uuid references public.departments (id) on delete set null,
  description    text not null,
  attachment_url text,
  priority       public.priority_level not null default 'medium',
  status         public.complaint_status not null default 'submitted',
  handler_type   public.handler_type not null default 'department',
  is_sensitive   boolean not null default false,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
-- 2.6 messages — anonymous complaint messages. sender_id is stored for
--     accountability/audit but is NEVER exposed to application access.
-- ----------------------------------------------------------------------------
create table if not exists public.messages (
  id           uuid primary key default gen_random_uuid(),
  complaint_id uuid not null references public.complaints (id) on delete cascade,
  sender_role  public.sender_role not null,
  sender_id    uuid not null references public.profiles (id) on delete cascade,
  body         text not null,
  created_at   timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
-- 2.7 identity_reveal_requests — student-controlled consent to reveal their
--     identity on a specific complaint. No reveal UI yet (Day 4+).
-- ----------------------------------------------------------------------------
create table if not exists public.identity_reveal_requests (
  id           uuid primary key default gen_random_uuid(),
  complaint_id uuid not null unique references public.complaints (id) on delete cascade,
  status       public.reveal_status not null default 'pending',
  revealed_at  timestamptz,
  revealed_to  uuid references public.profiles (id) on delete set null,
  created_at   timestamptz not null default now()
);

-- ============================================================================
-- 3. SEED DATA (ECS MVP only)
-- ============================================================================

insert into public.departments (name)
values ('ECS')
on conflict (name) do nothing;

insert into public.complaint_categories (name, is_sensitive)
values
  ('Academics',                    false),
  ('Labs',                         false),
  ('Faculty / Teaching',           false),
  ('Department Infrastructure',    false),
  ('Equipment',                    false),
  ('IT / Network',                 false),
  ('Department Administration',    false),
  ('Harassment / Ragging',         true)
on conflict (name) do nothing;

-- For this MVP every category maps to ECS.
insert into public.category_department_map (category_id, department_id)
select cc.id, d.id
from public.complaint_categories cc
cross join public.departments d
where d.name = 'ECS'
on conflict do nothing;

-- ============================================================================
-- 4. FUNCTIONS
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 4.1 get_app_role() — returns the CURRENT user's authoritative role from
--     public.profiles.role. SECURITY DEFINER so policies can read it without
--     being blocked by profiles RLS. Only ever returns the caller's own role,
--     so exposing it as an RPC is not a leak.
-- ----------------------------------------------------------------------------
create or replace function public.get_app_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role::text
  from public.profiles
  where id = auth.uid()
$$;

-- ----------------------------------------------------------------------------
-- 4.2 can_access_complaint(complaint_id) — visibility rule used by the RLS
--     policies on messages and identity_reveal_requests (the complaint row
--     already exists, so a table lookup is safe there):
--       student   -> only their own complaints
--       faculty   -> non-sensitive complaints (ECS)
--       admin     -> all ECS complaints (coordinator oversight)
--       committee -> sensitive complaints only
--     SECURITY DEFINER: implements the visibility rules itself and never
--     exposes identity columns.
--
--     NOTE: the base `complaints` table does NOT use this function in its
--     SELECT policy. With RLS, INSERT ... RETURNING requires the new row to
--     pass the SELECT policies, and the new row is not in the table yet, so a
--     self-lookup would always evaluate false. `complaints` therefore uses
--     direct, self-referential row policies instead (section 6.3).
-- ----------------------------------------------------------------------------
create or replace function public.can_access_complaint(p_complaint_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select case public.get_app_role()
    when 'student' then exists (
      select 1 from public.complaints c
      where c.id = p_complaint_id and c.student_id = auth.uid()
    )
    when 'faculty' then exists (
      select 1 from public.complaints c
      where c.id = p_complaint_id and c.is_sensitive = false
    )
    when 'admin' then exists (
      select 1 from public.complaints c
      where c.id = p_complaint_id
    )
    when 'committee' then exists (
      select 1 from public.complaints c
      where c.id = p_complaint_id and c.is_sensitive = true
    )
    else false
  end
$$;

-- ----------------------------------------------------------------------------
-- 4.3 handle_new_user() — creates a profile row for every new auth user with
--     the default role 'student'. department_id is left NULL for now: student
--     department membership is implicit (ECS MVP) and faculty/admin department
--     assignment is not configured yet.
-- ----------------------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, role)
  values (new.id, new.email, 'student')
  on conflict (id) do nothing;
  return new;
end;
$$;

-- ----------------------------------------------------------------------------
-- 4.4 derive_complaint_defaults() — BEFORE INSERT on complaints:
--       * ticket_number : CMP-XXXX from an atomic PostgreSQL sequence
--                         (collision-safe under concurrent submissions)
--       * is_sensitive  : always derived from the category (cannot be forged)
--       * handler_type  : committee for sensitive categories, else department
--       * department_id : derived from category_department_map (ECS)
-- ----------------------------------------------------------------------------
create sequence if not exists public.complaints_ticket_seq start 1;

create or replace function public.derive_complaint_defaults()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_category_is_sensitive boolean;
  v_department_id uuid;
begin
  if new.ticket_number is null then
    new.ticket_number := 'CMP-' || lpad(nextval('public.complaints_ticket_seq')::text, 4, '0');
  end if;

  select is_sensitive into v_category_is_sensitive
  from public.complaint_categories
  where id = new.category_id;

  new.is_sensitive := coalesce(v_category_is_sensitive, false);

  if new.is_sensitive then
    new.handler_type := 'committee';
  else
    new.handler_type := 'department';
  end if;

  select department_id into v_department_id
  from public.category_department_map
  where category_id = new.category_id
  limit 1;

  new.department_id := v_department_id;

  return new;
end;
$$;

-- ----------------------------------------------------------------------------
-- 4.5 messages_set_sender() — BEFORE INSERT on messages: the server enforces
--     sender_id = auth.uid() and derives sender_role from the caller's app
--     role, so a client cannot forge who sent a message.
-- ----------------------------------------------------------------------------
create or replace function public.messages_set_sender()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.sender_id := auth.uid();
  new.sender_role := case public.get_app_role()
    when 'student' then 'student'::public.sender_role
    when 'committee' then 'committee'::public.sender_role
    else 'staff'::public.sender_role
  end;
  return new;
end;
$$;

-- ----------------------------------------------------------------------------
-- 4.6 set_updated_at() — keeps complaints.updated_at fresh.
-- ----------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ============================================================================
-- 5. TRIGGERS
-- ============================================================================

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

drop trigger if exists complaints_derive_defaults on public.complaints;
create trigger complaints_derive_defaults
  before insert on public.complaints
  for each row execute function public.derive_complaint_defaults();

drop trigger if exists complaints_set_updated_at on public.complaints;
create trigger complaints_set_updated_at
  before update on public.complaints
  for each row execute function public.set_updated_at();

drop trigger if exists messages_set_sender on public.messages;
create trigger messages_set_sender
  before insert on public.messages
  for each row execute function public.messages_set_sender();

-- ============================================================================
-- 6. ROW LEVEL SECURITY
-- ============================================================================

alter table public.profiles                enable row level security;
alter table public.departments             enable row level security;
alter table public.complaint_categories    enable row level security;
alter table public.category_department_map enable row level security;
alter table public.complaints              enable row level security;
alter table public.messages                enable row level security;
alter table public.identity_reveal_requests enable row level security;

-- ----------------------------------------------------------------------------
-- 6.1 profiles — select-own only. NO insert/update/delete policies at all:
--     the sign-up trigger inserts, and a student can never change their own
--     role or department_id through the API (nor can anyone else).
-- ----------------------------------------------------------------------------
drop policy if exists profiles_select_own on public.profiles;
create policy profiles_select_own
  on public.profiles
  for select to authenticated
  using (id = auth.uid());

-- ----------------------------------------------------------------------------
-- 6.2 reference data (departments, complaint_categories,
--     category_department_map) — public reference data, no identity inside.
-- ----------------------------------------------------------------------------
drop policy if exists departments_select_all on public.departments;
create policy departments_select_all
  on public.departments
  for select to authenticated
  using (true);

drop policy if exists complaint_categories_select_all on public.complaint_categories;
create policy complaint_categories_select_all
  on public.complaint_categories
  for select to authenticated
  using (true);

drop policy if exists category_department_map_select_all on public.category_department_map;
create policy category_department_map_select_all
  on public.category_department_map
  for select to authenticated
  using (true);

-- ----------------------------------------------------------------------------
-- 6.3 complaints
--     SELECT uses direct, self-referential row policies (see note in 4.2:
--     this keeps INSERT ... RETURNING working for students) and is strictly
--     role-gated — there is NO unrestricted staff SELECT policy:
--       student   -> own rows only (student_id = auth.uid())
--       faculty   -> non-sensitive rows only
--       admin     -> all rows (ECS coordinator oversight)
--       committee -> sensitive rows only
--     INSERT is limited to students creating their own complaint.
--     Identity columns are additionally hidden by column-level grants
--     (section 7), so even a direct query of the base table cannot retrieve
--     student_id.
-- ----------------------------------------------------------------------------
drop policy if exists complaints_select_accessible on public.complaints;
drop policy if exists complaints_select_student on public.complaints;
drop policy if exists complaints_select_faculty on public.complaints;
drop policy if exists complaints_select_admin on public.complaints;
drop policy if exists complaints_select_committee on public.complaints;

create policy complaints_select_student
  on public.complaints
  for select to authenticated
  using (student_id = auth.uid());

create policy complaints_select_faculty
  on public.complaints
  for select to authenticated
  using (public.get_app_role() = 'faculty' and is_sensitive = false);

create policy complaints_select_admin
  on public.complaints
  for select to authenticated
  using (public.get_app_role() = 'admin');

create policy complaints_select_committee
  on public.complaints
  for select to authenticated
  using (public.get_app_role() = 'committee' and is_sensitive = true);

drop policy if exists complaints_insert_own on public.complaints;
create policy complaints_insert_own
  on public.complaints
  for insert to authenticated
  with check (public.get_app_role() = 'student' and student_id = auth.uid());

-- ----------------------------------------------------------------------------
-- 6.4 messages — visibility mirrors the parent complaint. sender_id is
--     enforced by the messages_set_sender trigger and hidden by grants.
-- ----------------------------------------------------------------------------
drop policy if exists messages_select_accessible on public.messages;
create policy messages_select_accessible
  on public.messages
  for select to authenticated
  using (public.can_access_complaint(complaint_id));

drop policy if exists messages_insert_accessible on public.messages;
create policy messages_insert_accessible
  on public.messages
  for insert to authenticated
  with check (public.can_access_complaint(complaint_id));

-- ----------------------------------------------------------------------------
-- 6.5 identity_reveal_requests — the student controls consent: only a
--     student may create or update a reveal request, and only for their own
--     complaint. Other roles can read requests for complaints they can see
--     (the table contains no identity information).
-- ----------------------------------------------------------------------------
drop policy if exists reveal_select_accessible on public.identity_reveal_requests;
create policy reveal_select_accessible
  on public.identity_reveal_requests
  for select to authenticated
  using (public.can_access_complaint(complaint_id));

drop policy if exists reveal_insert_student_own on public.identity_reveal_requests;
create policy reveal_insert_student_own
  on public.identity_reveal_requests
  for insert to authenticated
  with check (public.get_app_role() = 'student' and public.can_access_complaint(complaint_id));

drop policy if exists reveal_update_student_own on public.identity_reveal_requests;
create policy reveal_update_student_own
  on public.identity_reveal_requests
  for update to authenticated
  using (public.get_app_role() = 'student' and public.can_access_complaint(complaint_id))
  with check (public.get_app_role() = 'student' and public.can_access_complaint(complaint_id));

-- ============================================================================
-- 7. GRANTS — defense in depth
--    Strip the broad default grants Supabase applies, then grant exactly the
--    columns each role may touch. Identity columns (student_id, sender_id)
--    are NOT granted to `authenticated`, so even a direct DevTools query of
--    the base tables cannot retrieve them. service_role is left untouched
--    (server-side only, never used by the frontend).
-- ============================================================================

-- 7.0 Strip defaults on every Day 3 table.
revoke all on table public.profiles                 from anon, authenticated;
revoke all on table public.departments              from anon, authenticated;
revoke all on table public.complaint_categories     from anon, authenticated;
revoke all on table public.category_department_map  from anon, authenticated;
revoke all on table public.complaints               from anon, authenticated;
revoke all on table public.messages                 from anon, authenticated;
revoke all on table public.identity_reveal_requests from anon, authenticated;

-- 7.1 profiles — select own only (policies restrict to own row).
grant select (id, email, role, department_id, created_at)
  on public.profiles to authenticated;

-- 7.2 reference data — readable by signed-in users.
grant select on public.departments, public.complaint_categories, public.category_department_map
  to authenticated;

-- 7.3 complaints — SELECT excludes student_id; INSERT limited to the columns
--     a student may set (ticket_number/status/is_sensitive/handler_type/
--     department_id are derived by triggers).
grant select (id, ticket_number, category_id, department_id, description,
              attachment_url, priority, status, handler_type, is_sensitive,
              created_at, updated_at)
  on public.complaints to authenticated;

grant insert (student_id, category_id, description, attachment_url, priority)
  on public.complaints to authenticated;

-- 7.4 messages — SELECT excludes sender_id; INSERT limited to complaint_id +
--     body (sender columns are set by the messages_set_sender trigger).
grant select (id, complaint_id, sender_role, body, created_at)
  on public.messages to authenticated;

grant insert (complaint_id, body)
  on public.messages to authenticated;

-- 7.5 identity_reveal_requests — students may read their own, request a reveal
--     (insert complaint_id only, status always starts 'pending') and change
--     only the status (consent). revealed_at / revealed_to are server-managed.
grant select on public.identity_reveal_requests to authenticated;
grant insert (complaint_id) on public.identity_reveal_requests to authenticated;
grant update (status) on public.identity_reveal_requests to authenticated;

-- ============================================================================
-- 8. SAFE VIEWS (identity-free projections, security invoker so RLS applies)
-- ============================================================================

create or replace view public.complaints_staff_view
with (security_invoker = true)
as
select
  c.id,
  c.ticket_number,
  c.category_id,
  cc.name       as category,
  c.department_id,
  d.name        as department,
  c.description,
  c.attachment_url,
  c.priority,
  c.status,
  c.handler_type,
  c.is_sensitive,
  c.created_at,
  c.updated_at
from public.complaints c
left join public.complaint_categories cc on cc.id = c.category_id
left join public.departments d          on d.id   = c.department_id;

create or replace view public.messages_staff_view
with (security_invoker = true)
as
select
  m.id,
  m.complaint_id,
  m.sender_role,
  m.body,
  m.created_at
from public.messages m;

-- Strip any default grants on the views, then expose them read-only to
-- signed-in users. (Views are created first so the grants can reference them.)
revoke all on table public.complaints_staff_view from anon, authenticated;
revoke all on table public.messages_staff_view   from anon, authenticated;

grant select on public.complaints_staff_view to authenticated;
grant select on public.messages_staff_view   to authenticated;

-- ============================================================================
-- 9. INDEXES (MVP access patterns only — no excessive indexes)
-- ============================================================================

create index if not exists complaints_student_id_idx
  on public.complaints (student_id);

create index if not exists complaints_department_status_idx
  on public.complaints (department_id, status);

create index if not exists complaints_handler_type_idx
  on public.complaints (handler_type);

create index if not exists complaints_status_updated_at_idx
  on public.complaints (status, updated_at);

create index if not exists messages_complaint_created_idx
  on public.messages (complaint_id, created_at);

-- ticket_number uniqueness is enforced by the table's UNIQUE constraint
-- (which creates a unique index automatically).
